### ISSUE TITLE
Exponent has no digits error

### ISSUE THREAD

**Issue by doka1997** [avaneev/r8brain-free-src#28]
Hello @avaneev

I'm trying to use your library on a Raspberry Pi, but I'm getting the following errors when building:

```
In file included from r8brain-free-src/CDSPFIRFilter.h:18,
                 from r8brain-free-src/CDSPBlockConvolver.h:18,
                 from r8brain-free-src/CDSPResampler.h:21,
                 from process.cpp:3:
r8brain-free-src/CDSPSincFilterGen.h:330:29: error: exponent has no digits
  330 |                 if( Freq1 < 0x1p-42 )
      |                             ^~~~
r8brain-free-src/CDSPSincFilterGen.h:484:52: error: exponent has no digits
  484 |                 int IsZeroX = ( fabs( fd - 1.0 ) < 0x1p-42 );
      |                                                    ^~~~
r8brain-free-src/CDSPSincFilterGen.h:486:53: error: exponent has no digits
  486 |                 IsZeroX = ( IsZeroX || fabs( fd ) < 0x1p-42 );
      |                                                     ^~~~
```

I've used your library before and if I switch to that older commit (cb67707ea0db772c686fade1a47a368c2fb9b57b) I can build it and there are no problems... However with the current version, I'm running into the above issue.

**Comment by avaneev** [comment]
This issue is related to your compiler, which does not fully support C99 number specifications. `0x1p-42` is a C99 number. I'll consider changing it to a usual exponential notation. For now, you can safely replace it with 2.3e-13

**Comment by avaneev** [comment]
Please, also try to replace with 0x1.0p-42 to see if it works. I have not encountered such error before.

**Comment by doka1997** [comment]
The compiler on the machine is:

`Using built-in specs.`
`COLLECT_GCC=g++`
`COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/11/lto-wrapper`
`Target: aarch64-linux-gnu`
`Thread model: posix`
`Supported LTO compression algorithms: zlib zstd`
`gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)`

I've tried replacing 0x1p-42 with the 0x1.0p-42, but it didn't work - same error. 

It now works with the 2.3e-13. Thanks for your help!

**Comment by avaneev** [comment]
Thanks for the info. There's some uncertainty regarding support of such "power" definitions. Some sources say you need to specify -std=c++17 in GCC to enable them. But they are likely supported from the get-go if you compile C source. Other compilers just parse it as C99 constant, without relying on C++ specs. GCC 13.2 I use has no issues with such definitions.

**Comment by doka1997** [comment]
Indeed, specifying compiler flag `-std=c++17` resolves the issue, without having to modify the values in the CDSPSincFilterGen.h file.

**Comment by avaneev** [comment]
I've posted v6.5 which changed the `p` notation to `e` notation, so the `-std=c++17` switch is now not needed.
